app_name = "quantitative-risk-platform"
primary_region = "iad"

[build]

[env]
  STREAMLIT_SERVER_HEADLESS = "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8501

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[deploy]
  release_command = "echo 'Starting Streamlit app...'"