services:
  - type: web
    name: quantitative-risk-platform-stable
    env: python
    runtime: python-3.13.1  # Force specific Python 3.13.1 version
    build: |
      # Ensure we're using Python 3.13.1
      python --version
      
      # Clean pip cache to avoid conflicts
      pip cache purge || true
      
      # Upgrade core build tools
      python -m pip install --upgrade --no-cache-dir pip>=24.2
      python -m pip install --upgrade --no-cache-dir setuptools>=75.1.0 wheel>=0.44.0
      
      # Install requirements
      pip install --no-cache-dir -r requirements-render.txt
      
    start: streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: BACKEND_URL
        value: https://your-backend-url.onrender.com
      - key: PYTHON_VERSION
        value: "3.13.1"
      - key: PIP_NO_CACHE_DIR
        value: "1"