name: Release

on:
  push:
    tags:
      - 'v*'

env:
  PYTHON_VERSION: '3.11'

jobs:
  # Create GitHub Release
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Generate changelog
      run: |
        # Generate changelog from git commits
        git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD > CHANGELOG.md
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Extract tag name from ref
        TAG_NAME=${GITHUB_REF#refs/tags/}
        
        # Check if this is a prerelease
        if [[ "$TAG_NAME" == *"alpha"* ]] || [[ "$TAG_NAME" == *"beta"* ]] || [[ "$TAG_NAME" == *"rc"* ]]; then
          PRERELEASE_FLAG="--prerelease"
        else
          PRERELEASE_FLAG=""
        fi
        
        # Create release using GitHub CLI
        gh release create "$TAG_NAME" \
          --title "Release $TAG_NAME" \
          --notes-file CHANGELOG.md \
          $PRERELEASE_FLAG

  # Create deployment package
  package-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Create deployment package
      run: |
        # Create a deployment package
        mkdir -p dist/risk-platform
        
        # Copy application files
        cp -r backend/ dist/risk-platform/
        cp -r frontend/ dist/risk-platform/
        cp -r config/ dist/risk-platform/
        cp -r deployment/ dist/risk-platform/
        cp -r requirements/ dist/risk-platform/
        cp -r scripts/ dist/risk-platform/
        cp README.md dist/risk-platform/
        
        # Create archive
        cd dist
        tar -czf risk-platform-${GITHUB_REF#refs/tags/}.tar.gz risk-platform/
        zip -r risk-platform-${GITHUB_REF#refs/tags/}.zip risk-platform/
    
    - name: Upload release assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        
        # Upload deployment packages
        gh release upload "$TAG_NAME" \
          dist/risk-platform-$TAG_NAME.tar.gz \
          dist/risk-platform-$TAG_NAME.zip